/**
 * @fileoverview Admin registration authorization token codes index, complete with generators and inline revocation.
 */

import { useState } from 'react';
import { Plus, Ban } from 'lucide-react';
import DataTable from '../../components/common/DataTable';

// Pure generation helper outside of the React component context to satisfy purity rule
function generateRandomHex() {
  return Math.floor(1000 + Math.random() * 9000);
}

export default function AdminAuthCodes() {
  const [toast, setToast] = useState('');

  // Stateful auth codes list
  const [codes, setCodes] = useState([
    { code: 'TS-AUTH-9081', role: 'dept_head', createdBy: 'Super Admin Rohan', status: 'Active', created: '2026-05-25' },
    { code: 'TS-AUTH-8822', role: 'hr_admin', createdBy: 'Super Admin Rohan', status: 'Active', created: '2026-05-24' },
    { code: 'TS-AUTH-7710', role: 'dept_head', createdBy: 'Super Admin Rohan', status: 'Used', created: '2026-05-20' },
  ]);

  const handleGenerateCode = () => {
    const randomHex = generateRandomHex();
    const newCode = {
      code: `TS-AUTH-${randomHex}`,
      role: 'dept_head',
      createdBy: 'Super Admin Rohan',
      status: 'Active',
      created: new Date().toISOString().split('T')[0],
    };

    setCodes(prev => [newCode, ...prev]);
    triggerToast(`Generated active token code: ${newCode.code}`);
  };

  const handleRevokeCode = (codeStr) => {
    setCodes(prev => prev.map(c => c.code === codeStr ? { ...c, status: 'Revoked' } : c));
    triggerToast(`Revoked registration token code: ${codeStr}`);
  };

  const triggerToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(''), 2000);
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'Active':
        return <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">Active</span>;
      case 'Used':
        return <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider bg-slate-500/15 text-slate-400 border border-steel-600">Used</span>;
      default:
        return <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider bg-red-500/10 text-red-300 border border-red-500/20">Revoked</span>;
    }
  };

  const getRoleBadge = (role) => {
    return role === 'dept_head' 
      ? <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">Department Head</span>
      : <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-purple-500/10 text-purple-400 border border-purple-500/20">HR Admin</span>;
  };

  const columns = [
    {
      key: 'code',
      label: 'Onboarding Token Code',
      render: (val) => <span className="font-mono font-bold text-white tracking-wide">{val}</span>,
    },
    {
      key: 'role',
      label: 'Assigned Role Privilege',
      render: (val) => getRoleBadge(val),
    },
    {
      key: 'created',
      label: 'Generation Date',
    },
    {
      key: 'createdBy',
      label: 'Generated By',
    },
    {
      key: 'status',
      label: 'Token Status',
      render: (val) => getStatusBadge(val),
    },
    {
      key: 'actions',
      label: 'Security Moderation',
      render: (_, row) => (
        row.status === 'Active' ? (
          <button
            onClick={() => handleRevokeCode(row.code)}
            type="button"
            className="py-1 px-2.5 rounded bg-red-500/10 hover:bg-red-500/20 text-[10px] font-bold text-red-400 border border-red-500/20 flex items-center space-x-1 transition-all focus:outline-none"
          >
            <Ban className="w-3.5 h-3.5" />
            <span>Revoke Token</span>
          </button>
        ) : (
          <span className="text-xs text-slate-500 font-medium">Inactive</span>
        )
      ),
    },
  ];

  return (
    <div className="space-y-6 font-body">
      
      {/* Page Header */}
      <div className="border-b border-steel-700/60 pb-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-[10px] uppercase font-mono tracking-widest text-tata-gold">SECURITY AUTHORIZATION</span>
          <h1 className="text-2xl sm:text-3xl font-bold text-white mt-1">
            Staff Access Tokens
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 font-normal">
            Generate, monitor, and revoke internal access authorization tokens required during internal staff onboarding.
          </p>
        </div>

        <button
          onClick={handleGenerateCode}
          type="button"
          className="sm:self-end flex items-center justify-center py-2.5 px-5 rounded-xl text-xs sm:text-sm font-semibold bg-gradient-to-r from-tata-blue to-tata-light text-white shadow-lg hover:shadow-tata-blue/30 hover:scale-102 transition-all focus:outline-none"
        >
          <Plus className="w-4 h-4 mr-2" />
          Generate Access Token
        </button>
      </div>

      {toast && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs sm:text-sm font-bold rounded-xl animate-fadeIn">
          ✓ {toast}
        </div>
      )}

      {/* Main DataTable panel */}
      <div className="bg-steel-800 border border-steel-700/60 rounded-2xl p-5 shadow-xl">
        <DataTable
          columns={columns}
          data={codes}
          emptyMessage="No authorization codes generated yet."
        />
      </div>

    </div>
  );
}
